import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Container from '../layouts/Container'
import Topbar from '../layouts/Topbar'

const Experience: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>User : Experience</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <main className="">
          <Topbar />
        </main>
      </Container>
    </div>
  )
}

export default Experience
